# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(592, 418)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.choose_test = QtWidgets.QComboBox(self.centralwidget)
        self.choose_test.setGeometry(QtCore.QRect(190, 90, 131, 21))
        self.choose_test.setObjectName("choose_test")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 571, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.test_choice_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.test_choice_layout.setObjectName("test_choice_layout")
        self.choose_test1 = QtWidgets.QComboBox(self.centralwidget)
        self.choose_test1.setObjectName("choose_test1")
        self.test_choice_layout.addWidget(self.choose_test1)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setObjectName("start")
        self.test_choice_layout.addWidget(self.start)
        self.test_choice_layout1 = QtWidgets.QHBoxLayout()
        self.test_choice_layout1.setObjectName("test_choice_layout1")
        self.main_test_combo = QtWidgets.QComboBox(self.centralwidget)
        self.main_test_combo.setObjectName("main_test_combo")
        self.test_choice_layout1.addWidget(self.main_test_combo)
        self.sub_test_combo = QtWidgets.QComboBox(self.centralwidget)
        self.sub_test_combo.setObjectName("sub_test_combo")
        self.test_choice_layout1.addWidget(self.sub_test_combo)
        self.start1 = QtWidgets.QPushButton(self.centralwidget)
        self.start1.setObjectName("start1")
        self.test_choice_layout1.addWidget(self.start1)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setObjectName("exit")
        self.test_choice_layout1.addWidget(self.exit)
